name: Reset environment
run-name: Reset data on ${{ github.event.inputs.environment }}
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to reset
        required: true
        default: 'development'
        options:
          - staging
          - qa
          - development
jobs:
  reset-data:
    name: 'Reset data'
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-24.04
    outputs:
      outcome: ${{ steps.reset-data.outcome }}
    timeout-minutes: 60
    steps:
      - name: Clone country config resource package
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          path: './${{ github.event.repository.name }}'

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
      
          printf "%s\n" "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      
          HOST_IP="${{ vars.SSH_HOST || secrets.SSH_HOST }}"
          HOST_DOMAIN="${{ vars.DOMAIN }}"
          PORT="${{ vars.SSH_PORT || secrets.SSH_PORT }}"
      
          # Remove old entries
          ssh-keygen -R "$HOST_IP" || true
          ssh-keygen -R "$HOST_DOMAIN" || true
      
          # Add IP
          ssh-keyscan -p $PORT -t rsa,ecdsa,ed25519 $HOST_IP >> ~/.ssh/known_hosts
      
          # Add DOMAIN (this is what rsync is using)
          ssh-keyscan -p $PORT -t rsa,ecdsa,ed25519 $HOST_DOMAIN >> ~/.ssh/known_hosts
      
          chmod 600 ~/.ssh/known_hosts
      
          cat <<EOF > ~/.ssh/config
          Host *
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking yes
            UserKnownHostsFile ~/.ssh/known_hosts
            Port $PORT
          EOF
      
          chmod 600 ~/.ssh/config
      
          echo "Trusted hosts:"
          cat ~/.ssh/known_hosts
          
      - name: Update OpenCRVS known-hosts file
        working-directory: ${{ github.event.repository.name }}
        run: |
          HOST_IP="${{ vars.SSH_HOST || secrets.SSH_HOST }}"
          HOST_DOMAIN="${{ vars.DOMAIN }}"
          PORT="${{ vars.SSH_PORT || secrets.SSH_PORT }}"
      
          rm -f infrastructure/known-hosts
      
          # Add IP
          ssh-keyscan -p $PORT -H -t rsa,ecdsa,ed25519 $HOST_IP \
            >> infrastructure/known-hosts
      
          # Add domain (this is critical)
          ssh-keyscan -p $PORT -H -t rsa,ecdsa,ed25519 $HOST_DOMAIN \
            >> infrastructure/known-hosts
      
          echo "Updated infrastructure/known-hosts:"
          cat infrastructure/known-hosts

      - name: Reset data
        id: reset-data
        env:
          HOST: ${{ vars.DOMAIN }}
          ENV: ${{ vars.ENVIRONMENT_TYPE }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ vars.SSH_HOST }}
          SSH_PORT: ${{ vars.SSH_PORT }}
          REPLICAS: ${{ vars.REPLICAS }}
          MONGODB_ADMIN_USER: ${{ secrets.MONGODB_ADMIN_USER }}
          MONGODB_ADMIN_PASSWORD: ${{ secrets.MONGODB_ADMIN_PASSWORD }}
          ELASTICSEARCH_SUPERUSER_PASSWORD: ${{ secrets.ELASTICSEARCH_SUPERUSER_PASSWORD }}
          MINIO_ROOT_USER: ${{ secrets.MINIO_ROOT_USER }}
          MINIO_ROOT_PASSWORD: ${{ secrets.MINIO_ROOT_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          SSH_ARGS: ${{ vars.SSH_ARGS }}
        run: |
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST $SSH_ARGS "
            ELASTICSEARCH_ADMIN_USER=elastic \
            ELASTICSEARCH_ADMIN_PASSWORD=$ELASTICSEARCH_SUPERUSER_PASSWORD \
            MONGODB_ADMIN_USER=$MONGODB_ADMIN_USER \
            MONGODB_ADMIN_PASSWORD=$MONGODB_ADMIN_PASSWORD \
            MINIO_ROOT_USER=$MINIO_ROOT_USER \
            MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD \
            POSTGRES_USER=$POSTGRES_USER \
            POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
            /opt/opencrvs/infrastructure/clear-all-data.sh $REPLICAS"

          echo "Running migrations..."
          echo
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST $SSH_ARGS "
              ELASTICSEARCH_ADMIN_USER=elastic \
              ELASTICSEARCH_ADMIN_PASSWORD=$ELASTICSEARCH_SUPERUSER_PASSWORD \
              /opt/opencrvs/infrastructure/run-migrations.sh"
